# 网站的基本信息
site:
  tab: Nebulogue # 浏览器标签栏上显示的文本
  title: ✨Nebulogue # 网站的标题
  description: Wangzc2012's blog # 网站的描述，用于SEO等
  language: en # 网站的语言，例如 "en" 是英文
  favicon: /favicon.svg # 网站的图标，用于浏览器标签栏和其他地方显示
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: winter # 主题的浅色模式
    dark: dracula # 主题的深色模式
    code: github-dark # 代码块的主题 https://shiki.style/themes
  date_format: ddd MMM DD YYYY # 日期格式设置，支持自定义格式
  blog: # 博客相关配置
    pageSize: 8 # 每页显示的文章数量
  menu: # 菜单配置
    - id: home # 菜单项的唯一标识符
      text: Home # 菜单项显示的文本
      href: / # 菜单项链接的地址
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: About
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blogs
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: All blogs
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: learning
          text: learning blogs
          href: /blog/category/learning
          svg: "material-symbols:deployed-code-outline"
          target: _self
        - id: life
          text: Life blogs
          href: /blog/category/life
          svg: "material-symbols:earthquake-rounded"
          target: _self
        - id: tech
          text: Tech blogs
          href: /blog/category/tech
          svg: "material-symbols:deployed-code-outline"
          target: _self
        # 子菜单项配置
    - id: project
      text: Project
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: Friend
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: team
      text: Team
      href: /team
      svg: "ri:team-line"
      target: _self

# 用户的个人信息
user:
  name: Wangzc2012 # 用户名
  site: "https://nebulogue.netlify.app/" # 用户的网站链接
  avatar: /profile.png # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      - href: "https://github.com/wangzc2012"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/3546782877354264"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "tencent://message/?uin=2647784598" 
        ariaLabel: QQ
        title: QQ
        svg: "ri:qq-line" 
      - href: "mailto:2647784598@qq.com"  
        ariaLabel: Email
        title: Email
        svg: "ri:mail-line"
  footer:
    social:
      - href: "https://github.com/wangzc2012"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/3546782877354264"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "tencent://message/?uin=2647784598" 
        ariaLabel: QQ
        title: QQ
        svg: "ri:qq-line"  
      - href: "mailto:2647784598@qq.com"  
        ariaLabel: Email
        title: Email
        svg: "ri:mail-line"